import { ContentPost, ContentClient } from "./types";

interface EmailOptions {
  to: string;
  subject: string;
  htmlBody: string;
}

/**
 * Send an email (mock implementation - integrate with SendGrid, Resend, etc.)
 */
async function sendEmail(options: EmailOptions): Promise<void> {
  console.log(`[EMAIL] To: ${options.to}`);
  console.log(`[EMAIL] Subject: ${options.subject}`);
  console.log(`[EMAIL] Body: ${options.htmlBody.substring(0, 100)}...`);
}

/**
 * Send approval request email
 */
export async function sendApprovalEmail(
  post: ContentPost,
  client: ContentClient,
  approvalUrl: string
): Promise<void> {
  const htmlBody = `
    <h2>Content Ready for Approval</h2>
    <p>Hi ${client.name},</p>
    <p>Your generated blog post is ready for review:</p>
    <h3>${post.title}</h3>
    <p>${post.meta_description}</p>
    <p><a href="${approvalUrl}">Review and Approve in Dashboard</a></p>
    <hr>
    <p>This content was generated by Big Britches' AI content system.</p>
  `;

  await sendEmail({
    to: client.notification_email,
    subject: `Content Approval Required: "${post.title}"`,
    htmlBody,
  });
}

/**
 * Send published notification email
 */
export async function sendPublishedEmail(
  post: ContentPost,
  client: ContentClient,
  originalUrl: string
): Promise<void> {
  const platforms = [];
  if (client.platforms_enabled.blog) platforms.push("Blog");
  if (client.platforms_enabled.facebook) platforms.push("Facebook");
  if (client.platforms_enabled.instagram) platforms.push("Instagram");
  if (client.platforms_enabled.google_business) platforms.push("Google Business Profile");

  const htmlBody = `
    <h2>Content Published Successfully</h2>
    <p>Hi ${client.name},</p>
    <p>Your blog post has been published to the following platforms:</p>
    <ul>
      <li>Your Website: <a href="${originalUrl}">${post.title}</a></li>
      ${platforms.map((p) => `<li>${p}</li>`).join("\n")}
    </ul>
    <p>Check the dashboard for more details and analytics.</p>
    <hr>
    <p>This content was published by Big Britches' content distribution system.</p>
  `;

  await sendEmail({
    to: client.notification_email,
    subject: `Content Published: "${post.title}"`,
    htmlBody,
  });
}

/**
 * Send rejection email
 */
export async function sendRejectionEmail(
  post: ContentPost,
  client: ContentClient,
  reason: string
): Promise<void> {
  const htmlBody = `
    <h2>Content Rejected</h2>
    <p>Hi ${client.name},</p>
    <p>Your blog post "${post.title}" was rejected.</p>
    <p><strong>Reason:</strong> ${reason}</p>
    <p>You can request regeneration in your dashboard.</p>
    <hr>
    <p>This notification was sent by Big Britches' content system.</p>
  `;

  await sendEmail({
    to: client.notification_email,
    subject: `Content Rejected: "${post.title}"`,
    htmlBody,
  });
}

/**
 * Send generation error email
 */
export async function sendGenerationErrorEmail(
  client: ContentClient,
  error: string
): Promise<void> {
  const htmlBody = `
    <h2>Content Generation Error</h2>
    <p>Hi ${client.name},</p>
    <p>There was an error generating content for your account:</p>
    <p><strong>${error}</strong></p>
    <p>Please contact support if this issue persists.</p>
    <hr>
    <p>This notification was sent by Big Britches' content system.</p>
  `;

  await sendEmail({
    to: client.notification_email,
    subject: "Content Generation Error",
    htmlBody,
  });
}
